import { AndroidUpdate } from "@/components/android-update";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Bell, UserRound, Monitor, ShieldCheck, Workflow, SlidersHorizontal, Camera, LogOut, Volume2, RefreshCw, Plus, Pencil, Trash2, ExternalLink } from "lucide-react";
import { useAuthStore } from "@/store/auth.store";
import { useNotificationStore } from "@/store/notification.store";
import { useDeliveryStore, type DeliveryPreferences } from "@/store/delivery.store";
import { useNavigationStore } from "@/store/navigation.store";
import { useThemeStore, type Theme } from "@/store/theme.store";
import { uploadAvatar, updateOperator } from "@/features/operators/operators.api";
import { getAutoResponses, createAutoResponse, updateAutoResponse, deleteAutoResponse, type AutoResponseRule } from "@/features/inbox/inbox.api";
import { API_BASE } from "@/lib/api";
import { isAndroid, isNative } from "@/lib/api-config";
import { requestPushPermission, applyWebUpdate } from "@/lib/pwa";
import { getSession } from "@/lib/auth-session";
import { Button, Input, Modal, Select, Toggle, toast, useConfirm } from "@/components/ui";
import s from "./SettingsScreen.module.css";
const tabs = [{id:"profile",label:"Мой профиль",icon:UserRound},{id:"notifications",label:"Уведомления",icon:Bell},{id:"devices",label:"Устройства и вход",icon:ShieldCheck},{id:"appearance",label:"Приложение",icon:SlidersHorizontal},{id:"routing",label:"Работа команды",icon:Workflow}];
function Card({title,description,children}:{title:string;description?:string;children:ReactNode}) { return <section className={s.card}><h2>{title}</h2>{description&&<p className={s.description}>{description}</p>}<div className={s.cardBody}>{children}</div></section>; }
const statusOptions = [{value:"online",label:"На связи"},{value:"away",label:"Отошёл"},{value:"dnd",label:"Не беспокоить"},{value:"offline",label:"Не в сети"}];
export function SettingsScreen() {
  const auth=useAuthStore(), sound=useNotificationStore(), delivery=useDeliveryStore(), theme=useThemeStore();
  const [tab,setTab]=useState("profile"),[busy,setBusy]=useState(false),[name,setName]=useState(auth.operator?.name||""),[password,setPassword]=useState("");
  const [prefs,setPrefs]=useState<DeliveryPreferences>(delivery.preferences),[autorun,setAutorun]=useState(false);
  const [rules,setRules]=useState<AutoResponseRule[]>([]),[rule,setRule]=useState<Partial<AutoResponseRule>|null>(null);
  const [routeDraft,setRouteDraft]=useState(delivery.routing);
  const avatarInput=useRef<HTMLInputElement>(null), soundInput=useRef<HTMLInputElement>(null);
  const {confirm}=useConfirm();
  const manager=["admin","supervisor"].includes(auth.operator?.role||""), windows=isNative()&&!isAndroid();
  const run=async(action:()=>Promise<unknown>,success?:string)=>{setBusy(true);try{await action();if(success)toast.success(success)}catch(error){toast.error(error instanceof Error?error.message:"Не удалось выполнить действие")}finally{setBusy(false)}};
  useEffect(()=>{
    if(tab==="notifications")void delivery.loadPreferences().then(()=>setPrefs(useDeliveryStore.getState().preferences));
    if(tab==="devices")void delivery.loadDevices();
    if(tab==="routing"&&manager)void Promise.all([getAutoResponses().then(setRules),delivery.loadRouting().then(()=>setRouteDraft(useDeliveryStore.getState().routing))]).catch(error=>toast.error(error.message));
    if(tab==="appearance"&&windows)void import("@tauri-apps/plugin-autostart").then(plugin=>plugin.isEnabled()).then(setAutorun).catch(()=>undefined);
  },[tab]);
  const openScreen=(screen:"queue"|"visitors"|"operators"|"widget_settings"|"logs"|"dashboard")=>{
    useNavigationStore.setState({screen,mobileView:screen==="logs"?"logs":"workspace"});
  };
  return <div className={s.page}>
    <header className={s.header}><h1>Настройки</h1><p>Профиль, уведомления, устройства и оформление.</p></header>
    <div className={s.layout}><nav className={s.navigation} aria-label="Разделы настроек">{tabs.filter(item=>item.id!=="routing"||manager).map(item=><button key={item.id} aria-current={tab===item.id?"page":undefined} onClick={()=>setTab(item.id)}><item.icon size={18}/>{item.label}</button>)}<button onClick={()=>openScreen("logs")}><Monitor size={18}/>Диагностика</button></nav>
      <div className={s.content}>
      {tab==="profile"&&<>
        <Card title="Личный профиль" description="Эти имя и фотографию видит клиент, когда вы отвечаете."><div className={s.profile}><button className={s.avatar} aria-label="Изменить фотографию" onClick={()=>avatarInput.current?.click()}>{auth.operator?.avatar_url?<img src={new URL(auth.operator.avatar_url,API_BASE).href} alt=""/>:<span>{auth.operator?.name?.slice(0,1)||"О"}</span>}<Camera size={15}/></button><div><strong>{auth.operator?.name}</strong><p>{auth.operator?.email}</p><small>{auth.operator?.role==="admin"?"Администратор":auth.operator?.role==="supervisor"?"Руководитель команды":"Оператор"}</small></div></div>
          <input ref={avatarInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(file)void run(async()=>{const result=await uploadAvatar(auth.operator!.id,file);auth.setOperator({...auth.operator!,avatar_url:result.avatar_url})},"Фотография обновлена")}}/>
          <Input label="Ваше имя" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/><Button disabled={busy||!name.trim()||name===auth.operator?.name} onClick={()=>void run(async()=>{await updateOperator(auth.operator!.id,{name:name.trim()});auth.setOperator({...auth.operator!,name:name.trim()})},"Имя сохранено")}>Сохранить имя</Button>
        </Card>
        <Card title="Доступность" description="Статус синхронизируется между вашими устройствами."><Select value={auth.operator?.status||"offline"} options={statusOptions} onChange={value=>void run(()=>auth.updateOperatorStatus(value as "online"|"away"|"dnd"|"offline"))}/></Card>
        <Card title="Пароль" description="После смены пароля потребуется снова войти на всех устройствах."><Input type="password" autoComplete="new-password" label="Новый пароль" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} maxLength={128} placeholder="Не менее 8 символов"/><Button variant="secondary" disabled={busy||password.length<8} onClick={()=>void run(async()=>{await updateOperator(auth.operator!.id,{password});setPassword("");await auth.logout()},"Пароль изменён. Войдите снова.")}>Изменить пароль</Button></Card>
        <Button variant="dangerGhost" icon={<LogOut size={16}/>} onClick={()=>void confirm({title:"Выйти из приложения?",message:"Неотправленные ответы останутся в очереди вашего аккаунта.",confirmText:"Выйти"}).then(ok=>ok?auth.logout():undefined)}>Выйти на этом устройстве</Button>
      </>}
      {tab==="notifications"&&<>
        <Card title="Сообщения и напоминания" description="Настройки действуют на всех ваших устройствах. Во внешние push-службы отправляются только ID и общее уведомление.">
          <Toggle label="Уведомлять о новых обращениях" checked={prefs.enabled} onChange={enabled=>setPrefs({...prefs,enabled})}/>
          <Toggle label="Новые сообщения клиентов" checked={prefs.new_messages} onChange={new_messages=>setPrefs({...prefs,new_messages})}/>
          <Toggle label="Напоминать о клиентах без ответа" checked={prefs.escalation} onChange={escalation=>setPrefs({...prefs,escalation})}/>
          <Toggle label="Показывать текст после загрузки с сервера" checked={prefs.show_preview} onChange={show_preview=>setPrefs({...prefs,show_preview})}/>
          <Button variant="secondary" icon={<Bell size={16}/>} onClick={()=>void run(requestPushPermission,"Разрешение на уведомления проверено")}>Включить на этом устройстве</Button>
        </Card>
        <Card title="Тихие часы" description="В это время уведомления и звуки будут выключены, включая напоминания."><Toggle label="Не беспокоить по расписанию" checked={!!prefs.dnd_start} onChange={enabled=>setPrefs({...prefs,dnd_start:enabled?"22:00":null,dnd_end:enabled?"09:00":null})}/>{prefs.dnd_start&&<div className={s.row}><Input label="С" type="time" value={prefs.dnd_start} onChange={e=>setPrefs({...prefs,dnd_start:e.target.value})}/><Input label="До" type="time" value={prefs.dnd_end||"09:00"} onChange={e=>setPrefs({...prefs,dnd_end:e.target.value})}/></div>}<Select label="Часовой пояс" value={prefs.timezone} options={[{value:"Asia/Yekaterinburg",label:"Екатеринбург · UTC+5"},{value:"Europe/Moscow",label:"Москва · UTC+3"},{value:"Asia/Novosibirsk",label:"Новосибирск · UTC+7"},{value:"Asia/Vladivostok",label:"Владивосток · UTC+10"},{value:"UTC",label:"UTC"}]} onChange={timezone=>setPrefs({...prefs,timezone})}/><Button disabled={busy} onClick={()=>void run(()=>delivery.savePreferences(prefs),"Уведомления настроены")}>Сохранить уведомления</Button></Card>
        <Card title="Звук этого устройства" description={isAndroid()?"Звук в фоне настраивается в Android → Приложения → Живая Сказка → Уведомления.":"Эти настройки относятся к открытому приложению."}><Toggle label="Звуки в приложении" checked={sound.soundEnabled} onChange={sound.setSoundEnabled}/><label className={s.range}>Громкость · {Math.round(sound.soundVolume*100)}%<input type="range" min="0" max="1" step="0.05" value={sound.soundVolume} onChange={e=>sound.setSoundVolume(Number(e.target.value))}/></label><div className={s.row}><Button variant="secondary" icon={<Volume2 size={16}/>} onClick={()=>sound.previewSound("new_message")}>Послушать</Button><Button variant="ghost" onClick={()=>soundInput.current?.click()}>Свой звук</Button>{sound.customSound&&<Button variant="ghost" onClick={()=>sound.setCustomSound(null,null)}>Сбросить</Button>}</div>{sound.customSoundName&&<small>{sound.customSoundName}</small>}<input ref={soundInput} type="file" accept="audio/*" hidden onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){toast.error("Выберите звук до 1 МБ");return}const reader=new FileReader();reader.onload=()=>sound.setCustomSound(String(reader.result),file.name);reader.readAsDataURL(file)}}/></Card>
      </>}
      {tab==="devices"&&<Card title="Где выполнен вход" description="Можно завершить потерянный или ненужный сеанс. Токены и адреса push здесь не показываются."><div className={s.row}><Button variant="secondary" size="sm" icon={<RefreshCw size={15}/>} onClick={()=>void delivery.loadDevices()}>Обновить</Button></div>{delivery.error&&<p role="alert" className={s.error}>{delivery.error}</p>}{delivery.loading&&<p>Загружаем устройства…</p>}{delivery.sessions.map(item=>{const device=delivery.devices.find(d=>d.installation_id===item.installation_id);return <div className={s.device} key={item.id}><div className={s.deviceIcon}><Monitor size={20}/></div><div><strong>{item.client_name||device?.name||"Приложение"}{item.current&&<span className={s.badge}>Это устройство</span>}</strong><p>{device?.platform||"Сеанс"} · {new Date(item.last_used_at||item.created_at).toLocaleString("ru-RU")}</p><small>{device?.enabled?"Уведомления подключены":"Уведомления не подключены"}</small></div><Button variant="dangerGhost" size="sm" onClick={()=>void confirm({title:"Завершить этот сеанс?",message:item.current?"Вы выйдете из приложения на этом устройстве.":"На выбранном устройстве потребуется снова ввести пароль.",confirmText:"Завершить"}).then(ok=>ok?item.current?auth.logout():delivery.revokeSession(item.id):undefined).catch(error=>toast.error(error.message))}>Выйти</Button></div>})}{!delivery.loading&&!delivery.sessions.length&&!delivery.error&&<p className={s.description}>Других активных сеансов нет.</p>}</Card>}
      {tab==="appearance"&&<>
        <Card title="Оформление" description="Спокойные тёплые тона в светлой и тёмной теме."><Select label="Тема" value={theme.theme==="fairytale"?"light":theme.theme} options={[{value:"system",label:"Как в системе"},{value:"light",label:"Светлая"},{value:"dark",label:"Тёмная"}]} onChange={value=>theme.setTheme(value as Theme)}/><Select label="Плотность интерфейса" value={theme.density} options={[{value:"comfortable",label:"Комфортная"},{value:"compact",label:"Компактная"}]} onChange={value=>theme.setDensity(value as "comfortable"|"compact")}/><Toggle label="Тёмная тема вечером, с 19:00 до 07:00" checked={theme.autoTimeTheme} onChange={theme.setAutoTimeTheme}/></Card>
        {windows&&<Card title="Поведение Windows"><Toggle label="При закрытии оставаться в трее" checked={sound.closeToTray} onChange={sound.setCloseToTray}/><Toggle label="Запускать при входе в Windows" checked={autorun} onChange={enabled=>void run(async()=>{const plugin=await import("@tauri-apps/plugin-autostart");if(enabled)await plugin.enable();else await plugin.disable();setAutorun(await plugin.isEnabled())})}/><p className={s.description}>Для фоновых уведомлений приложение должно работать. Закрытие в трей сохраняет связь.</p></Card>}
        <Card title="Версия приложения"><div className={s.version}><img src="/book-mark.svg" alt=""/><div><strong>Живая Сказка</strong><p>{__APP_VERSION__}</p></div></div>{isAndroid()&&<AndroidUpdate/>}{!isAndroid()&&<Button variant="secondary" icon={<RefreshCw size={16}/>} onClick={()=>void run(async()=>{if(isNative())toast.info(await (await import("@/components/updater")).checkForUpdatesManually());else await applyWebUpdate()})}>Проверить обновление</Button>}<p className={s.description}>Стабильные обновления публикуются после проверки совместимости сервера и приложений.</p></Card>
      </>}
      {tab==="routing"&&manager&&<>
        <Card title="Распределение диалогов" description="Автоматически направляйте новые обращения операторам на связи с наименьшей нагрузкой."><Toggle label="Автоматическое распределение" checked={routeDraft.automatic} onChange={automatic=>setRouteDraft({...routeDraft,automatic})}/><div className={s.row}><Input label="Напомнить без ответа, минут" type="number" min={1} max={60} value={routeDraft.escalation_minutes} onChange={e=>setRouteDraft({...routeDraft,escalation_minutes:Number(e.target.value)})}/><Input label="Статус «Отошёл» при простое, минут" type="number" min={1} max={120} value={routeDraft.idle_minutes} onChange={e=>setRouteDraft({...routeDraft,idle_minutes:Number(e.target.value)})}/></div><Button disabled={busy} onClick={()=>void run(()=>delivery.saveRouting(routeDraft),"Правила распределения сохранены")}>Сохранить правила</Button></Card>
        <Card title="Автоответ в очереди" description="Поддержите клиента сообщением, если он ждёт оператора.">{rules.map(item=><div className={s.rule} key={item.id}><Toggle label={`Через ${item.delay_seconds} сек.`} checked={item.is_active} onChange={is_active=>void run(async()=>{const changed=await updateAutoResponse(item.id,{is_active});setRules(list=>list.map(r=>r.id===item.id?changed:r))})}/><p>{item.message}</p><div className={s.row}><Button variant="ghost" size="sm" icon={<Pencil size={14}/>} onClick={()=>setRule(item)}>Изменить</Button><Button variant="dangerGhost" size="sm" icon={<Trash2 size={14}/>} onClick={()=>void confirm({title:"Удалить автоответ?",message:"Он перестанет отправляться клиентам.",confirmText:"Удалить",danger:true}).then(ok=>ok?run(async()=>{await deleteAutoResponse(item.id);setRules(list=>list.filter(r=>r.id!==item.id))}):undefined)}>Удалить</Button></div></div>)}<Button variant="secondary" icon={<Plus size={16}/>} onClick={()=>setRule({trigger_type:"queue_timeout",delay_seconds:60,message:"",is_active:true})}>Добавить автоответ</Button></Card>
        <Card title="Инструменты команды"><div className={s.tools}>{[{screen:"visitors" as const,label:"Посетители"},{screen:"queue" as const,label:"Очередь обращений"},{screen:"operators" as const,label:"Сотрудники"},{screen:"dashboard" as const,label:"Статистика"},{screen:"widget_settings" as const,label:"Виджет на сайте"}].map(item=><button key={item.screen} onClick={()=>openScreen(item.screen)}>{item.label}<ExternalLink size={15}/></button>)}</div></Card>
      </>}
      </div>
    </div>
    <Modal open={!!rule} onClose={()=>setRule(null)} title={rule?.id?"Изменить автоответ":"Новый автоответ"} footer={<Button disabled={busy||!rule?.message?.trim()} onClick={()=>void run(async()=>{const data={trigger_type:"queue_timeout",delay_seconds:Number(rule!.delay_seconds),message:rule!.message!,is_active:rule!.is_active};if(rule!.id)await updateAutoResponse(rule!.id,data);else await createAutoResponse(data);setRules(await getAutoResponses());setRule(null)},"Автоответ сохранён")}>Сохранить</Button>}>{rule&&<div className={s.cardBody}><Input label="Ожидание в секундах" type="number" min={10} max={3600} value={rule.delay_seconds||60} onChange={e=>setRule({...rule,delay_seconds:Number(e.target.value)})}/><label className={s.field}>Сообщение<textarea value={rule.message||""} maxLength={10000} onChange={e=>setRule({...rule,message:e.target.value})}/></label></div>}</Modal>
  </div>;
}
