import { useEffect, useMemo, useRef, useState } from "react";
import { Globe, Search, RefreshCw, MessageSquare, Send, MapPin, Monitor, Clock, ExternalLink, Ban, ArrowUpRight } from "lucide-react";
import { getVisitorsPage, getVisitorPath, startChatWithVisitor } from "@/features/visitors/visitors.api";
import { sendInvitation, getChatSession, blockVisitorBySession } from "@/features/inbox/inbox.api";
import { useAuthStore } from "@/store/auth.store";
import { useInboxStore } from "@/store/inbox.store";
import { useNavigationStore } from "@/store/navigation.store";
import { getSocket } from "@/lib/socket";
import { Avatar, Button, Modal, Select, toast, useConfirm } from "@/components/ui";
import type { SiteVisitor, VisitorPathStep } from "@/types/visitor";
import s from "./VisitorsScreen.module.css";
const name=(visitor:SiteVisitor)=>visitor.visitor_name||`Гость ${visitor.visitor_id.slice(-6)}`;
const safeLink=(value:string)=>{try{const url=new URL(value);return /^https?:$/.test(url.protocol)?url.href:null}catch{return null}};
const when=(value:string)=>value?new Date(value).toLocaleString("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
export function VisitorsScreen() {
  const operator=useAuthStore(state=>state.operator),[rows,setRows]=useState<SiteVisitor[]>([]),[mode,setMode]=useState("online"),[query,setQuery]=useState(""),[date,setDate]=useState(""),[country,setCountry]=useState("");
  const [total,setTotal]=useState(0),[online,setOnline]=useState(0),[withChat,setWithChat]=useState(0),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [selected,setSelected]=useState<SiteVisitor|null>(null),[path,setPath]=useState<VisitorPathStep[]>([]),[invite,setInvite]=useState(false),[message,setMessage]=useState("Здравствуйте! Помочь вам выбрать сказку?"),[busy,setBusy]=useState(false);
  const generation=useRef(0),{confirm}=useConfirm();
  const load=async(append=false)=>{
    const request=++generation.current;setLoading(true);setError("");
    try{
      const response=await getVisitorsPage({limit:60,offset:append?rows.length:0,online:mode==="online"?true:undefined,has_chat:mode==="with_chat"?true:undefined,search:query.trim()||undefined,date:date||undefined,country:country||undefined});
      if(request!==generation.current)return;
      setRows(previous=>append?[...previous,...response.items.filter(item=>!previous.some(old=>old.visitor_id===item.visitor_id))]:response.items);
      setMore(response.has_more);setTotal(response.total??response.items.length);setOnline(response.online_total??response.items.filter(item=>item.is_online).length);setWithChat(response.with_chat_total??response.items.filter(item=>item.has_chat).length);
    }catch{if(request===generation.current)setError("Не удалось обновить список. Проверьте соединение.")}finally{if(request===generation.current)setLoading(false)}
  };
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>{clearTimeout(timer);generation.current++}},[mode,query,date,country]);
  useEffect(()=>{const socket=getSocket();let debounce:ReturnType<typeof setTimeout>|undefined;const refresh=()=>{clearTimeout(debounce);debounce=setTimeout(()=>void load(),1000)};socket.on('visitor_online',refresh);socket.on('visitor_offline',refresh);socket.on('connect',refresh);const timer=setInterval(refresh,30000);return()=>{clearInterval(timer);clearTimeout(debounce);socket.off('visitor_online',refresh);socket.off('visitor_offline',refresh);socket.off('connect',refresh)}},[mode,query,date,country]);
  useEffect(()=>{if(!selected)return;let cancelled=false;setPath([]);void getVisitorPath(selected.visitor_id).then(result=>{if(!cancelled)setPath(result)});return()=>{cancelled=true}},[selected?.visitor_id]);
  const countries=useMemo(()=>Array.from(new Set(rows.map(row=>row.country).filter((value):value is string=>!!value))).sort(),[rows]);
  const openChat=async(visitor:SiteVisitor)=>{
    setBusy(true);try{const id=visitor.chat_session_id||(await startChatWithVisitor(visitor.visitor_id)).session_id;const session=await getChatSession(id);useInboxStore.getState().upsertSession(session);useInboxStore.getState().openSession(session);useNavigationStore.setState({screen:'inbox',mobileView:'chat-conversation'})}catch(failure){toast.error(failure instanceof Error?failure.message:'Не удалось открыть диалог')}finally{setBusy(false)}
  };
  const inviteVisitor=async()=>{if(!selected||!operator)return;setBusy(true);try{const result=await sendInvitation({visitorId:selected.visitor_id,operatorId:operator.id,message});if(!result.ok)throw new Error(result.error||'Не удалось отправить приглашение');setInvite(false);toast.success('Приглашение отправлено посетителю')}catch(failure){toast.error(failure instanceof Error?failure.message:'Не удалось отправить приглашение')}finally{setBusy(false)}};
  return <section className={s.page}><header className={s.header}><div><h1>Посетители сайта</h1><p>Кто сейчас на сайте и кому может понадобиться помощь.</p></div><Button variant="secondary" icon={<RefreshCw size={16}/>} onClick={()=>void load()} disabled={loading}>Обновить</Button></header>
    <div className={s.metrics}><article><Globe size={21}/><strong>{online}</strong><span>сейчас на сайте</span></article><article><MessageSquare size={21}/><strong>{withChat}</strong><span>с перепиской</span></article><article><Clock size={21}/><strong>{total}</strong><span>по выбранным условиям</span></article></div>
    <nav className={s.tabs} aria-label="Посетители">{[{id:'online',label:'Сейчас онлайн'},{id:'with_chat',label:'С диалогом'},{id:'all',label:'Все визиты'}].map(item=><button key={item.id} aria-pressed={mode===item.id} onClick={()=>{setMode(item.id);if(item.id==='online')setDate('')}}>{item.label}</button>)}</nav>
    <div className={s.toolbar}><div className={s.search}><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Имя, город или страница" aria-label="Поиск посетителей"/></div><label className={s.date}>Дата визита<input type="date" value={date} onChange={event=>{setDate(event.target.value);if(event.target.value)setMode('all')}}/></label><Select value={country||'all'} onChange={value=>setCountry(value==='all'?'':value)} options={[{value:'all',label:'Все страны'},...Array.from(new Set([...countries,...(country?[country]:[])])).map(value=>({value,label:value}))]}/></div>
    {error&&<p role="alert" className={s.error}>{error}</p>}
    <div className={s.table}><table><thead><tr><th>Посетитель</th><th>Смотрит сейчас</th><th>Город и устройство</th><th>Активность</th><th/></tr></thead><tbody>{rows.map(visitor=><tr key={visitor.visitor_id} onClick={()=>setSelected(visitor)}><td><div className={s.person}><Avatar name={name(visitor)} size="sm"/><div><strong>{name(visitor)}</strong><small><i data-online={visitor.is_online}/>{visitor.is_online?'На сайте':`Был ${when(visitor.last_seen_at)}`}</small></div></div></td><td><span className={s.pageTitle}>{visitor.current_page_title||'Страница сайта'}</span><small>{safeLink(visitor.current_page)?new URL(visitor.current_page).pathname:visitor.current_page||'—'}</small></td><td><span>{visitor.city||visitor.country||'Не определено'}</span><small>{[visitor.browser,visitor.os].filter(Boolean).join(' · ')||'—'}</small></td><td><span>{visitor.session_count||1} визит{(visitor.session_count||1)===1?'':'ов'}</span><small>{visitor.has_chat?'Есть переписка':'Пока без диалога'}</small></td><td><button className={s.open} aria-label={`Открыть посетителя ${name(visitor)}`} onClick={event=>{event.stopPropagation();setSelected(visitor)}}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className={s.empty}><Globe size={30}/><h2>{loading?'Обновляем список…':mode==='online'?'На сайте пока тихо':'Визиты не найдены'}</h2><p>{mode==='online'?'Посетители появятся здесь автоматически.':'Попробуйте другие условия поиска.'}</p></div>}</div>
    {more&&<Button variant="secondary" disabled={loading} onClick={()=>void load(true)}>{loading?'Загружаем…':'Показать ещё'}</Button>}
    <Modal open={!!selected&&!invite} onClose={()=>setSelected(null)} title={selected?name(selected):'Посетитель'} width={540} footer={selected&&<><Button variant="secondary" icon={<MessageSquare size={15}/>} disabled={busy} onClick={()=>void openChat(selected)}>{selected.has_chat?'Открыть переписку':'Начать диалог'}</Button>{selected.is_online&&<Button icon={<Send size={15}/>} onClick={()=>setInvite(true)}>Пригласить в чат</Button>}</>}>{selected&&<div className={s.visitor}><div className={s.facts}><span><MapPin size={15}/>{[selected.city,selected.country].filter(Boolean).join(', ')||'География не определена'}</span><span><Monitor size={15}/>{[selected.browser,selected.os].filter(Boolean).join(' · ')||'Устройство не определено'}</span><span><Clock size={15}/>Впервые: {when(selected.first_seen_at)}</span></div><h3>Путь по сайту</h3>{(path.length?path:[{page:selected.current_page,title:selected.current_page_title,is_current:true}]).map((step,index)=><div className={s.step} key={index}><i/><div>{safeLink(step.page)?<a href={safeLink(step.page)!} target="_blank" rel="noreferrer noopener">{step.title||new URL(step.page).pathname}<ExternalLink size={12}/></a>:<span>{step.title||'Страница'}</span>}<small>{step.visited_at?when(step.visited_at):'Последняя открытая страница'}</small></div></div>)}<button className={s.block} onClick={()=>void confirm({title:'Заблокировать посетителя?',message:'Активные диалоги закроются. Посетитель не сможет писать с этой гостевой учётной записью.',confirmText:'Заблокировать',danger:true}).then(ok=>ok?blockVisitorBySession(selected.visitor_id).then(()=>{setSelected(null);void load()}):undefined).catch(error=>toast.error(error.message))}><Ban size={14}/>Заблокировать спам</button></div>}</Modal>
    <Modal open={invite&&!!selected} onClose={()=>setInvite(false)} title="Пригласить в разговор" footer={<Button disabled={busy||!message.trim()} onClick={()=>void inviteVisitor()}>{busy?'Отправляем…':'Отправить приглашение'}</Button>}><div className={s.invitation}><p>Посетитель увидит ваше имя и сообщение. Диалог начнётся, когда он откроет приглашение.</p><label>Сообщение посетителю<textarea value={message} maxLength={1000} onChange={event=>setMessage(event.target.value)}/></label></div></Modal>
  </section>;
}
