import { useEffect, useState } from "react";
import { Mail, Phone, Globe, Copy, Pencil, Plus, X, ArrowRightLeft, CircleCheck, Star, Tag, Clock, MapPin, Monitor, ExternalLink, Trash2 } from "lucide-react";
import { useInboxStore } from "@/store/inbox.store";
import { useAuthStore } from "@/store/auth.store";
import { updateContact, getVisitorSessions, setSessionPriority, type VisitorSessionsResponse } from "@/features/inbox/inbox.api";
import { getVisitorPath } from "@/features/visitors/visitors.api";
import { closeConversation } from "@/lib/open-conversation";
import { getSessionDisplayName } from "@/utils/avatar";
import { parseUserAgent } from "@/utils/parse-ua";
import { Avatar, Button, Input, Modal, Select, toast, useConfirm } from "@/components/ui";
import type { VisitorPathStep } from "@/types/visitor";
import s from "./ChatDetails.module.css";
function link(value:string|null|undefined){if(!value)return null;try{const url=new URL(value);return /^https?:$/.test(url.protocol)?url.href:null}catch{return null}}
function ContactLine({icon:Icon,label,value,href}:{icon:typeof Mail;label:string;value:string|null;href?:string}) {
  return <div className={s.contact}><Icon size={16}/><div><span>{label}</span>{value?href?<a href={href}>{value}</a>:<strong>{value}</strong>:<em>Не указан</em>}</div>{value&&<button aria-label={`Скопировать ${label.toLowerCase()}`} onClick={()=>void navigator.clipboard.writeText(value).then(()=>toast.success("Скопировано")).catch(()=>toast.error("Не удалось скопировать"))}><Copy size={14}/></button>}</div>;
}
export function ChatDetails() {
  const state=useInboxStore(),operator=useAuthStore(store=>store.operator),session=state.activeSession;
  const [tab,setTab]=useState("client"),[editing,setEditing]=useState(false),[form,setForm]=useState({name:"",email:"",phone:"",revision:1});
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[note,setNote]=useState(""),[noteId,setNoteId]=useState<string|null>(null);
  const [tagName,setTagName]=useState(""),[tagColor,setTagColor]=useState("#ab612f");
  const [history,setHistory]=useState<VisitorSessionsResponse|null>(null),[path,setPath]=useState<VisitorPathStep[]>([]),[historyLoading,setHistoryLoading]=useState(false);
  const {confirm}=useConfirm();
  useEffect(()=>{if(!session?.visitor_id)return;let cancelled=false;setHistoryLoading(true);void Promise.all([getVisitorSessions(session.visitor_id),getVisitorPath(session.visitor_id)]).then(([history,path])=>{if(!cancelled){setHistory(history);setPath(path)}}).catch(()=>undefined).finally(()=>{if(!cancelled)setHistoryLoading(false)});return()=>{cancelled=true}},[session?.visitor_id]);
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await action()}catch(failure){setError(failure instanceof Error?failure.message:"Не удалось сохранить изменение")}finally{setBusy(false)}};
  if(!session)return <aside className={s.empty}><span>Карточка клиента появится здесь</span></aside>;
  const name=getSessionDisplayName(session.visitor_name,session.visitor_id),canManage=!session.operator_id||session.operator_id===operator?.id||['admin','supervisor'].includes(operator?.role||'');
  const device=parseUserAgent(session.user_agent||"");
  const edit=()=>{setForm({name:session.visitor_name||"",email:session.visitor_email||"",phone:session.visitor_phone||"",revision:session.contact_revision||1});setError("");setEditing(true)};
  const journey=path.length?path:session.current_page?[{page:session.current_page,title:session.current_page_title||"Текущая страница",is_current:true}]:[];
  return <aside className={s.aside}><header className={s.header}><div className={s.identity}><Avatar name={name} size="md"/><div><h2>{name}</h2><small>{session.is_vip?"Особое внимание":"Клиент Живой Сказки"}</small></div>{canManage&&<button aria-label="Изменить контакты" onClick={edit}><Pencil size={15}/></button>}</div></header>
    <nav className={s.tabs} aria-label="Карточка клиента">{[{id:"client",title:"Клиент"},{id:"notes",title:"Заметки"},{id:"history",title:"История"}].map(item=><button key={item.id} aria-current={tab===item.id?"page":undefined} onClick={()=>setTab(item.id)}>{item.title}{item.id==="notes"&&state.notes.length>0&&<small>{state.notes.length}</small>}</button>)}</nav>
    <div className={s.body}>{error&&!editing&&<p className={s.error} role="alert">{error}</p>}
      {tab==="client"&&<>
        <section className={s.section}><h3>Контакты</h3><ContactLine icon={Mail} label="Почта" value={session.visitor_email} href={session.visitor_email?`mailto:${encodeURIComponent(session.visitor_email)}`:undefined}/><ContactLine icon={Phone} label="Телефон" value={session.visitor_phone} href={session.visitor_phone?`tel:${session.visitor_phone.replace(/[^+\d]/g,"")}`:undefined}/>{canManage&&(!session.visitor_email||!session.visitor_phone)&&<button className={s.textButton} onClick={edit}><Plus size={13}/>Добавить контакт</button>}</section>
        {session.form_data&&Object.keys(session.form_data).some(key=>!['email','phone','__labels'].includes(key))&&<section className={s.section}><h3>Ответы клиента</h3>{Object.entries(session.form_data).filter(([key])=>!['email','phone','__labels'].includes(key)).map(([key,value])=><div className={s.fact} key={key}><span>{String((session.form_data?.__labels as Record<string,string>|undefined)?.[key]||key)}</span><strong>{typeof value==='string'?value:JSON.stringify(value)}</strong></div>)}</section>}
        <section className={s.section}><h3>Диалог</h3><div className={s.fact}><span>Отвечает</span><strong>{session.operator_name||state.operators.find(item=>item.id===session.operator_id)?.name||"В общей очереди"}</strong></div><div className={s.fact}><span>Статус</span><strong>{session.status==="closed"?"Завершён":session.status==="with_operator"?"С оператором":session.status==="ai"?"С помощником":"Ждёт ответа"}</strong></div><div className={s.fact}><span>Оценка</span><strong>{session.rating?`${session.rating} из 5`:"Пока нет"}</strong></div>{session.rating_comment&&<p className={s.feedback}>{session.rating_comment}</p>}
          {canManage&&<><Select label="Приоритет" value={session.priority||"normal"} options={[{value:"normal",label:"Обычный"},{value:"high",label:"Высокий"},{value:"urgent",label:"Срочный"},{value:"low",label:"Низкий"}]} onChange={priority=>void run(()=>state.changeActiveSessionPriority(priority as "normal"|"high"|"urgent"|"low"))}/><button className={s.vip} aria-pressed={session.is_vip} onClick={()=>void run(async()=>{await setSessionPriority(session.id,session.priority,!session.is_vip,operator?.id);await state.loadSessions()})}><Star size={15}/>{session.is_vip?"Особое внимание включено":"Уделить особое внимание"}</button></>}
        </section>
        <section className={s.section}><h3>Метки</h3><div className={s.tags}>{state.sessionTags.map(item=><span key={item.id}><i style={{background:item.tag?.color||tagColor}}/>{item.tag?.name||"Метка"}<button aria-label={`Убрать метку ${item.tag?.name}`} onClick={()=>void run(()=>state.detachSessionTag(item.tag_id))}><X size={11}/></button></span>)}{!state.sessionTags.length&&<small>Добавьте метки, чтобы легче находить диалоги.</small>}</div><Select value="" onChange={id=>void run(()=>state.attachExistingTag(id))} options={state.allTags.filter(tag=>!state.sessionTags.some(item=>item.tag_id===tag.id)).map(tag=>({value:tag.id,label:tag.name}))} placeholder="Добавить готовую метку"/><form className={s.newTag} onSubmit={event=>{event.preventDefault();void run(async()=>{await state.createTagAndAttach(tagName,tagColor);setTagName("")})}}><input aria-label="Название новой метки" value={tagName} maxLength={60} onChange={event=>setTagName(event.target.value)} placeholder="Новая метка"/><input aria-label="Цвет метки" type="color" value={tagColor} onChange={event=>setTagColor(event.target.value)}/><button type="submit" disabled={busy||!tagName.trim()} aria-label="Создать метку"><Plus size={16}/></button></form></section>
        <section className={s.section}><h3>На сайте</h3>{link(session.current_page)&&<a className={s.pageLink} href={link(session.current_page)!} target="_blank" rel="noreferrer noopener"><Globe size={16}/><span>{session.current_page_title||new URL(session.current_page!).pathname}<small>{new URL(session.current_page!).hostname}</small></span><ExternalLink size={13}/></a>}<div className={s.fact}><span><MapPin size={12}/>Город</span><strong>{[session.city,session.country].filter(Boolean).join(", ")||"Не определён"}</strong></div><div className={s.fact}><span><Monitor size={12}/>Устройство</span><strong>{device}</strong></div><div className={s.fact}><span>Источник</span><strong>{session.utm_source||(!session.referrer?"Прямой переход":link(session.referrer)?new URL(session.referrer!).hostname:"Переход по ссылке")}</strong></div>{session.utm_campaign&&<div className={s.fact}><span>Кампания</span><strong>{session.utm_campaign}</strong></div>}</section>
      </>}
      {tab==="notes"&&<section className={s.section}><h3>Заметки команды</h3><p className={s.hint}>Клиент их не видит. Здесь удобно хранить важные детали заказа и договорённости.</p><form onSubmit={event=>{event.preventDefault();void run(async()=>{if(noteId)await state.updateNote(noteId,note);else await state.createNote(note);setNote("");setNoteId(null)})}}><textarea aria-label="Заметка о клиенте" value={note} maxLength={5000} rows={4} onChange={event=>setNote(event.target.value)} placeholder="Что важно помнить о клиенте"/><div className={s.noteActions}><Button size="sm" disabled={busy||!note.trim()} type="submit">{noteId?"Сохранить":"Добавить заметку"}</Button>{noteId&&<button type="button" onClick={()=>{setNoteId(null);setNote("")}}>Отмена</button>}</div></form>{state.notes.map(item=><article className={s.note} key={item.id}><p>{item.note}</p><footer><span>{state.operators.find(op=>op.id===item.operator_id)?.name||"Оператор"}<time>{new Date(item.created_at).toLocaleDateString("ru-RU")}</time></span>{(item.operator_id===operator?.id||['admin','supervisor'].includes(operator?.role||''))&&<><button aria-label="Редактировать заметку" onClick={()=>{setNoteId(item.id);setNote(item.note)}}><Pencil size={13}/></button><button aria-label="Удалить заметку" onClick={()=>void confirm({title:"Удалить заметку?",message:"Она исчезнет у всех сотрудников.",confirmText:"Удалить",danger:true}).then(ok=>ok?run(()=>state.deleteNote(item.id)):undefined)}><Trash2 size={13}/></button></>}</footer></article>)}</section>}
      {tab==="history"&&<>
        <section className={s.section}><h3>Путь клиента</h3>{journey.map((step,index)=><div className={s.journey} key={`${step.page}-${index}`}><i/><div>{link(step.page)?<a href={link(step.page)!} target="_blank" rel="noreferrer noopener">{step.title||new URL(step.page).pathname}</a>:<span>{step.title||"Страница"}</span>}<small>{step.is_current?"Сейчас здесь":step.visited_at?new Date(step.visited_at).toLocaleString("ru-RU"):step.is_referrer?"Источник перехода":""}</small></div></div>)}{!journey.length&&<p className={s.hint}>История переходов пока не сохранена.</p>}</section>
        <section className={s.section}><h3>Предыдущие обращения <small>{history?.total_sessions??0}</small></h3>{historyLoading&&<p className={s.hint}>Загружаем историю…</p>}{history?.sessions.filter(item=>item.id!==session.id).map(item=><button className={s.past} key={item.id} onClick={()=>{state.upsertSession(item);state.openSession(item)}}><Clock size={15}/><span><strong>{new Date(item.created_at).toLocaleDateString("ru-RU")}</strong><small>{item.last_message_text||`${item.messages_count||0} сообщений`}</small></span><small>{item.status==="closed"?"Завершён":"Открыт"}</small></button>)}{!historyLoading&&!history?.sessions.some(item=>item.id!==session.id)&&<p className={s.hint}>Это первое обращение с этого устройства.</p>}</section>
      </>}
    </div>
    {canManage&&session.status!=="closed"&&<footer className={s.footer}><Button variant="secondary" size="sm" icon={<ArrowRightLeft size={14}/>} onClick={()=>window.dispatchEvent(new Event("chat-transfer-request"))}>Передать</Button><Button variant="ghost" size="sm" icon={<CircleCheck size={14}/>} onClick={()=>void closeConversation(session)}>Завершить</Button></footer>}
    <Modal open={editing} onClose={()=>!busy&&setEditing(false)} title="Контакты клиента" footer={<Button disabled={busy} onClick={()=>void run(async()=>{const updated=await updateContact(session.id,{visitor_name:form.name.trim()||null,visitor_email:form.email.trim()||null,visitor_phone:form.phone.trim()||null,contact_revision:form.revision});state.upsertSession({...session,...updated});setEditing(false)})}>Сохранить</Button>}><div className={s.form}><Input label="Имя" value={form.name} maxLength={200} onChange={event=>setForm({...form,name:event.target.value})}/><Input label="Почта" type="email" value={form.email} maxLength={254} onChange={event=>setForm({...form,email:event.target.value})}/><Input label="Телефон" type="tel" value={form.phone} maxLength={50} onChange={event=>setForm({...form,phone:event.target.value})}/>{error&&<p role="alert" className={s.error}>{error}</p>}</div></Modal>
  </aside>;
}
