import { useEffect, useRef, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { ArrowDownLeft, ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, Globe2, Info, Laptop, LayoutDashboard, LockKeyhole, MessageCircle, Paperclip, Search, Send, Settings2, ShieldCheck, Smartphone, Smile, Tag, Users, Wifi, X, Zap } from "lucide-react";
import "@fontsource-variable/inter";
import "./operator-preview.css";

// Isolated design entry. No authentication, live API, sockets or real client data.
type Surface = "windows" | "android" | "widget";
type Message = { text: string; kind: "visitor" | "operator" | "note"; time: string };
type Chat = { id: number; name: string; initials: string; color: string; preview: string; time: string; count: number; tag: string; waiting?: boolean; messages: Message[] };
const initialChats: Chat[] = [
  { id:1,name:"Анна Сергеева",initials:"АС",color:"peach",preview:"А имя ребёнка будет в самой сказке?",time:"12:42",count:2,tag:"Выбирает книгу",waiting:true,messages:[
    {text:"Здравствуйте! Хочу заказать книгу в подарок дочке. Ей скоро 5 лет.",kind:"visitor",time:"12:39"},
    {text:"Анна, здравствуйте! Помогу выбрать сказку. Что любит ваша дочка — приключения, животных или волшебство?",kind:"operator",time:"12:40"},
    {text:"Волшебство и единорогов 🦄",kind:"visitor",time:"12:41"},
    {text:"А имя ребёнка будет в самой сказке?",kind:"visitor",time:"12:42"}]},
  {id:2,name:"Михаил Волков",initials:"МВ",color:"sage",preview:"Какое фото лучше подойдёт для книги?",time:"12:40",count:1,tag:"Фото для книги",waiting:true,messages:[{text:"Добрый день. Подскажите, какая фотография лучше подойдёт для книги?",kind:"visitor",time:"12:40"}]},
  {id:3,name:"Екатерина Белова",initials:"ЕБ",color:"sand",preview:"Успеет ли подарок к субботе?",time:"12:38",count:1,tag:"Доставка",waiting:true,messages:[{text:"Здравствуйте! Успеет ли подарок к субботе?",kind:"visitor",time:"12:38"}]},
  {id:4,name:"Ольга Миронова",initials:"ОМ",color:"rose",preview:"Вы: Пожалуйста, буду рядом!",time:"12:31",count:0,tag:"В работе",messages:[{text:"Спасибо, теперь всё понятно!",kind:"visitor",time:"12:30"},{text:"Пожалуйста, буду рядом!",kind:"operator",time:"12:31"}]},
  {id:5,name:"Посетитель #184",initials:"Г",color:"stone",preview:"Вы: Можно выбрать любую историю",time:"12:24",count:0,tag:"Первое обращение",messages:[{text:"А можно выбрать другую сказку?",kind:"visitor",time:"12:23"},{text:"Можно выбрать любую историю из каталога.",kind:"operator",time:"12:24"}]},
  {id:6,name:"Дмитрий Крылов",initials:"ДК",color:"sage",preview:"Спасибо за помощь с заказом!",time:"11:58",count:0,tag:"В работе",messages:[{text:"Спасибо за помощь с заказом!",kind:"visitor",time:"11:58"}]},
];
const answers = [
  {label:"Персонализация",text:"Да, имя вашей дочки будет в самой истории — она станет главной героиней сказки. Подскажите, как её зовут?"},
  {label:"Выбор фото",text:"Лучше всего подойдёт чёткий портрет при дневном свете, где хорошо видно лицо. Можете прикрепить фото сюда, и я помогу выбрать."},
  {label:"Сроки доставки",text:"Подскажите ваш город и дату праздника. Я проверю срок изготовления и доставки."},
];
function Brand(){return <div className="brand"><img src="/book-mark.svg" alt=""/><div><strong>Живая Сказка</strong><span>Забота о клиентах</span></div></div>}
function Avatar({chat,small=false}:{chat:Chat;small?:boolean}){return <span className={`avatar ${chat.color} ${small?"small":""}`}>{chat.initials}</span>}
function IconButton({children,label,onClick}:{children:ReactNode;label:string;onClick?:()=>void}){return <button type="button" className="icon-button" aria-label={label} title={label} onClick={onClick}>{children}</button>}

function Preview(){
  const requested=new URLSearchParams(location.search).get("view");
  const [surface,setSurface]=useState<Surface>(requested==="android"||requested==="widget"?requested:"windows");
  const [chats,setChats]=useState(initialChats);
  const [activeId,setActiveId]=useState(1);
  const [filter,setFilter]=useState("all");
  const [query,setQuery]=useState("");
  const [section,setSection]=useState("chats");
  const [mobileChat,setMobileChat]=useState(new URLSearchParams(location.search).has("chat"));
  const [details,setDetails]=useState(true);
  const [note,setNote]=useState(false);
  const [drafts,setDrafts]=useState<Record<number,string>>({});
  const [snippets,setSnippets]=useState(false);
  const [transfer,setTransfer]=useState(false);
  const [toast,setToast]=useState("");
  const [widgetOpen,setWidgetOpen]=useState(true);
  const search=useRef<HTMLInputElement>(null);
  const messageEnd=useRef<HTMLDivElement>(null);
  const active=chats.find(chat=>chat.id===activeId)!;
  const draft=drafts[activeId]||"";
  const waiting=chats.filter(chat=>chat.waiting).length;
  const unread=chats.reduce((sum,chat)=>sum+chat.count,0);
  const visible=chats.filter(chat=>(!query||`${chat.name} ${chat.preview}`.toLowerCase().includes(query.toLowerCase()))&&(filter!=="waiting"||chat.waiting)&&(filter!=="mine"||!chat.waiting));
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();search.current?.focus()}if(event.key==="Escape"){setTransfer(false);setSnippets(false);setMobileChat(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(timer)}},[toast]);
  useEffect(()=>{messageEnd.current?.scrollIntoView({block:"nearest"})},[active.messages.length,activeId]);
  function chooseSurface(next:Surface){setSurface(next);setSection("chats");history.replaceState(null,"",`?view=${next}`)}
  function chooseChat(id:number){setActiveId(id);setMobileChat(true);setSection("chats");setNote(false);setTransfer(false)}
  function setDraft(value:string){setDrafts(old=>({...old,[activeId]:value}))}
  function send(){if(!draft.trim())return;const message:Message={text:draft.trim(),kind:note?"note":"operator",time:"12:43"};setChats(old=>old.map(chat=>chat.id===activeId?{...chat,count:note?chat.count:0,waiting:note?chat.waiting:false,preview:`${note?"Заметка":"Вы"}: ${message.text}`,messages:[...chat.messages,message]}:chat));setDraft("");setSnippets(false)}
  function closeChat(){setChats(old=>old.map(chat=>chat.id===activeId?{...chat,waiting:false,count:0,tag:"Завершён"}:chat));setToast("Диалог завершён в макете. История сохранена.")}
  const nav=<>{[{id:"chats",label:"Диалоги",icon:MessageCircle},{id:"visitors",label:"Посетители",icon:Users},{id:"answers",label:"Ответы",icon:Zap},{id:"overview",label:"Обзор",icon:LayoutDashboard}].map(item=><button key={item.id} className={`nav-item ${section===item.id?"active":""}`} onClick={()=>{setSection(item.id);setMobileChat(false)}}><item.icon/><span>{item.label}</span>{item.id==="chats"&&unread>0&&<b>{unread}</b>}</button>)}</>;
  const list=<aside className="chat-list">
    <div className="list-heading"><div><span className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>Диалоги <span>{chats.length}</span></h1></div><IconButton label="Справка по очереди" onClick={()=>setToast("Сначала отвечайте клиентам во вкладке «Ждут ответа».")}><CircleHelp/></IconButton></div>
    <label className="chat-search"><Search/><input ref={search} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Найти диалог" aria-label="Найти диалог"/><kbd>Ctrl K</kbd></label>
    <div className="list-tabs" role="tablist" aria-label="Очередь диалогов">{[["all","Все",chats.length],["waiting","Ждут ответа",waiting],["mine","Мои",chats.length-waiting]].map(([value,label,count])=><button key={value} role="tab" aria-selected={filter===value} className={filter===value?"selected":""} onClick={()=>setFilter(String(value))}>{label}<span>{count}</span></button>)}</div>
    <div className="list-section"><span>{filter==="mine"?"В работе":"Сегодня"}</span><span>Сначала новые <ChevronDown size={12}/></span></div>
    <div className="conversation-scroll">{visible.map(chat=><button key={chat.id} className={`conversation ${activeId===chat.id?"chosen":""}`} onClick={()=>chooseChat(chat.id)}><Avatar chat={chat}/><div className="conversation-content"><div className="conversation-title"><strong>{chat.name}</strong><time>{chat.time}</time></div><div className="conversation-preview"><span>{chat.preview}</span>{chat.count>0&&<b>{chat.count}</b>}</div><div className="conversation-meta"><span><Globe2 size={11}/> Сайт</span>{chat.waiting?<span className="waiting"><Clock3 size={11}/> Ждёт ответа</span>:<span>{chat.tag}</span>}</div></div></button>)}</div>
    {!visible.length&&<p className="empty">Диалогов не найдено. Попробуйте другое имя.</p>}
    <div className="queue-tip"><i className="presence-dot"/><div><strong>Вы принимаете обращения</strong><span>Новые диалоги появятся здесь</span></div></div>
  </aside>;
  const contact=<aside className="contact-panel">
    <div className="contact-heading"><strong>О клиенте</strong><IconButton label="Закрыть карточку клиента" onClick={()=>setDetails(false)}><X/></IconButton></div>
    <div className="contact-profile"><Avatar chat={active}/><h2>{active.name}</h2><span><i className="presence-dot"/> Сейчас на сайте</span></div>
    <div className="contact-block"><div className="section-title">Контакты <button onClick={()=>setToast("В приложении здесь будет редактирование контактов.")}>Изменить</button></div><dl><dt>Email</dt><dd>{active.id===1?"anna@example.com":"Пока не указан"}</dd><dt>Телефон</dt><dd className="muted">Пока не указан</dd></dl></div>
    <div className="contact-block"><div className="section-title">Метки <Tag size={14}/></div><div className="tags"><span>{active.tag}</span><button onClick={()=>setToast("Метки: доставка, выбор книги, оплата.")}>+</button></div></div>
    <div className="contact-block"><div className="section-title">Сейчас смотрит <ArrowUpRight size={14}/></div><div className="page-card"><BookOpen/><div><strong>Персональная сказка</strong><span>Каталог / Сказочные истории</span></div></div><div className="journey"><div><i/><span>Главная страница<small>12:35</small></span></div><div><i/><span>Каталог книг<small>12:36</small></span></div><div className="current"><i/><span>Сказочные истории<small>12:38 · сейчас</small></span></div></div></div>
    <div className="contact-block"><div className="section-title">Источник обращения</div><p className="source"><Globe2 size={16}/> Яндекс · поиск</p><span className="muted small-text">Первый визит · 8 минут на сайте</span></div>
    <button className="history-button" onClick={()=>setToast("Это первое обращение демонстрационного клиента.")}><Clock3 size={15}/> История диалогов <ChevronRight size={15}/></button>
  </aside>;
  const thread=<main className="thread">
    <div className="thread-heading"><button className="back-button icon-button" onClick={()=>setMobileChat(false)} aria-label="К списку диалогов"><ArrowLeft/></button><Avatar chat={active} small/><div className="thread-person"><h2>{active.name}</h2><span><i className="presence-dot"/> На сайте <i className="separator"/> Первый диалог</span></div><div className="thread-actions"><IconButton label="Карточка клиента" onClick={()=>{setDetails(value=>!value);if(surface==="android")setToast(`${active.name} · ${active.tag} · Первый диалог`)}}><Info/></IconButton><div className="transfer-wrap"><IconButton label="Передать диалог" onClick={()=>setTransfer(value=>!value)}><Users/></IconButton>{transfer&&<div className="transfer-menu"><strong>Передать диалог</strong>{["Мария","Алексей"].map(name=><button key={name} onClick={()=>{setTransfer(false);setToast(`Диалог передан: ${name} (демо)`)}}>{name} · в сети <ArrowRight size={14}/></button>)}</div>}</div><button className="resolve-button" onClick={closeChat}><Check size={16}/><span>{active.tag==="Завершён"?"Завершён":"Завершить"}</span></button></div></div>
    <div className="context-bar"><Globe2 size={13}/><span>zhivaya-skazka.ru</span><ChevronRight size={12}/><span>Сказочные истории</span>{active.waiting&&<span className="response-timer"><Clock3 size={13}/> Ждёт 1 мин</span>}</div>
    <div className="message-scroll"><div className="date-marker">Сегодня, 14 сентября</div><div className="system-event"><ArrowDownLeft size={12}/> Клиент написал с сайта</div>{active.messages.map((message,index)=><div className={`message-row ${message.kind}`} key={`${active.id}-${index}`}>{message.kind==="visitor"&&<Avatar chat={active} small/>}<div className="message-bubble">{message.kind==="note"&&<strong className="note-label"><LockKeyhole size={12}/> Заметка для команды</strong>}<p>{message.text}</p><span className="message-time">{message.kind==="operator"&&"Вы · "}{message.time}{message.kind==="operator"&&<CheckCheck size={13}/>}</span></div></div>)}<div ref={messageEnd}/></div>
    <div className={`composer ${note?"internal-note":""}`}><div className="composer-tabs"><button className={!note?"active":""} onClick={()=>setNote(false)}><MessageCircle size={14}/> Ответ клиенту</button><button className={note?"active":""} onClick={()=>setNote(true)}><LockKeyhole size={13}/> Заметка</button><span>{note?"Видна только команде":"Видит только клиент"}</span></div><textarea value={draft} onChange={event=>setDraft(event.target.value)} placeholder={note?"Что важно знать коллегам об этом клиенте?":"Напишите ответ. Для шаблонов нажмите /"} aria-label={note?"Внутренняя заметка":"Ответ клиенту"} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();send()}if(event.key==="/"&&!draft)setSnippets(true)}}/>
    {snippets&&<div className="snippet-menu">{answers.map(answer=><button key={answer.label} onClick={()=>{setDraft(answer.text);setSnippets(false)}}><Zap size={14}/><span>{answer.label}</span><ArrowUpRight size={14}/></button>)}</div>}
    <div className="composer-bottom"><IconButton label="Прикрепить файл" onClick={()=>setToast("В рабочем приложении: фото, PDF и документы до 10 МБ.")}><Paperclip/></IconButton><IconButton label="Добавить улыбку" onClick={()=>setDraft(`${draft} 🙂`)}><Smile/></IconButton><button className="quick-answer" onClick={()=>setSnippets(value=>!value)}><Zap size={15}/><span>Быстрые ответы</span></button><button className="send-button" disabled={!draft.trim()} onClick={send}>{note?"Сохранить":"Отправить"}<Send size={14}/></button></div></div>
    <div className="composer-hint"><ShieldCheck size={12}/><span>Черновик сохранён в макете</span><span>Enter — отправить · Shift + Enter — новая строка</span></div>
  </main>;
  const alternate=<main className="alternate"><span className="eyebrow">ЖИВАЯ СКАЗКА / РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>{section==="answers"?"Отвечайте быстрее":section==="visitors"?"Клиенты на сайте":"Рабочий день"}</h1><p>{section==="answers"?"Сохраните свой тон общения в готовых фразах.":"Демонстрационные данные для выбора интерфейса."}</p>{section==="answers"?answers.map(answer=><button className="answer-card" key={answer.label} onClick={()=>{setDraft(answer.text);setSection("chats");setMobileChat(true)}}><div><Zap size={19}/><strong>{answer.label}</strong><ArrowUpRight size={17}/></div><p>{answer.text}</p><span>Использовать в текущем диалоге →</span></button>):section==="visitors"?chats.slice(0,4).map(chat=><button className="visitor-card" key={chat.id} onClick={()=>chooseChat(chat.id)}><Avatar chat={chat}/><div><strong>{chat.name}</strong><span>На сайте · {chat.tag}</span></div><ChevronRight/></button>):<><div className="metrics"><div><span>Ждут ответа</span><strong>{waiting}</strong></div><div><span>В работе</span><strong>{chats.length-waiting}</strong></div><div><span>Непрочитанные</span><strong>{unread}</strong></div></div><div className="overview-note"><Clock3/><div><strong>Всё начинается с ответа</strong><p>Здесь будут время первого ответа, пропущенные обращения и оценки клиентов.</p></div></div><button className="primary" onClick={()=>setSection("chats")}>Перейти к диалогам <ArrowRight size={17}/></button></>}</main>;
  return <div className="preview-page"><header className="preview-toolbar"><div><span className="preview-name">Живая Сказка <span>/</span> Оператор</span><p>Направление интерфейса · версия 8</p></div><nav className="surface-picker" aria-label="Вариант интерфейса">{([{id:"windows",label:"Windows",icon:Laptop},{id:"android",label:"Android",icon:Smartphone},{id:"widget",label:"Виджет",icon:MessageCircle}] as const).map(item=><button key={item.id} aria-pressed={surface===item.id} className={surface===item.id?"active":""} onClick={()=>chooseSurface(item.id)}><item.icon size={15}/><span>{item.label}</span></button>)}</nav><span className="demo-label"><i/> Интерактивный макет</span></header>
    <div className={`preview-stage surface-${surface}`}>
      {surface==="windows"&&<section className="desktop-window"><header className="app-topbar"><Brand/><span className="workspace-name">Служба заботы <ChevronDown size={13}/></span><div className="topbar-right"><span className="connection"><Wifi size={13}/> На связи</span><button className="operator-status" onClick={()=>setToast("Статусы: в сети, отошёл, не беспокоить, не в сети.")}><i className="presence-dot"/> В сети <ChevronDown size={12}/></button><span className="operator-avatar">М</span><span className="operator-name">Мария</span></div></header><div className={`desktop-body ${!details?"details-hidden":""} ${section!=="chats"?"alternate-body":""}`}><nav className="app-rail" aria-label="Разделы приложения">{nav}<div className="rail-bottom"><IconButton label="Настройки" onClick={()=>setToast("Здесь будут настройки уведомлений, команды и виджета.")}><Settings2/></IconButton><span>v8</span></div></nav>{section==="chats"?<>{list}{thread}{details&&contact}</>:alternate}</div></section>}
      {surface==="android"&&<div className="mobile-composition"><div className="mobile-caption"><span className="eyebrow">ANDROID / SAMSUNG S22 ULTRA</span><h2>Ваши клиенты.<br/>Всегда под рукой.</h2><p>Одна задача на экране. Крупные действия. Быстрый переход из уведомления прямо в диалог.</p><div className="mobile-feature"><MessageCircle/><div><strong>Знакомая переписка</strong><span>Ответы, файлы и заметки рядом</span></div></div><div className="mobile-feature"><Bell/><div><strong>Важное не потеряется</strong><span>Новые обращения и время ожидания</span></div></div><button className="text-link" onClick={()=>setMobileChat(value=>!value)}>{mobileChat?"Показать список диалогов":"Показать открытый диалог"}<ArrowRight size={17}/></button></div><section className="phone-frame"><div className="phone-status"><b>12:43</b><div><span>5G</span><Wifi size={12}/><span className="battery"/></div></div>{!mobileChat&&<header className="phone-brand"><Brand/><span className="operator-avatar">М</span></header>}<div className="phone-content">{section!=="chats"?alternate:mobileChat?thread:list}</div>{!mobileChat&&<nav className="mobile-nav" aria-label="Разделы мобильного приложения">{nav}</nav>}<div className="gesture-bar"/></section></div>}
      {surface==="widget"&&<div className="widget-composition"><div className="widget-caption"><span className="eyebrow">НА САЙТЕ / ВИДЖЕТ ПОДДЕРЖКИ</span><h2>Начать разговор<br/>очень просто.</h2><p>Свой бренд, живой оператор и понятный следующий шаг. Без лишних форм перед первым сообщением.</p><div className="widget-chips"><span><Check size={14}/> В стиле сайта</span><span><Check size={14}/> Удобно с телефона</span></div><button className="text-link" onClick={()=>setWidgetOpen(value=>!value)}>{widgetOpen?"Свернуть чат":"Открыть чат"}<ArrowRight size={17}/></button></div><div className="widget-example">{widgetOpen&&<section className="visitor-widget"><header><Brand/><IconButton label="Свернуть виджет" onClick={()=>setWidgetOpen(false)}><X/></IconButton></header><div className="widget-team"><div className="team-avatars"><span>М</span><span>А</span></div><div><strong>Поможем создать вашу сказку</strong><span><i className="presence-dot"/> Команда на связи</span></div></div><div className="widget-messages"><span className="date-marker">Сегодня</span><div className="widget-operator"><span className="mini-avatar">М</span><div><strong>Мария <span>· Служба заботы</span></strong><p>Здравствуйте! Помогу выбрать историю, подготовить фото или разобраться с заказом.</p></div></div><div className="widget-prompts">{["Помогите выбрать книгу","Вопрос по заказу","Как подготовить фото?"].map(text=><button key={text} onClick={()=>setDraft(text)}>{text}<ArrowUpRight size={13}/></button>)}</div></div><div className="widget-input"><textarea aria-label="Сообщение в виджете" placeholder="Напишите нам…" value={draft} onChange={event=>setDraft(event.target.value)}/><div><IconButton label="Вложение посетителя" onClick={()=>setToast("Виджет поддержит отправку фотографии.")}><Paperclip/></IconButton><button aria-label="Отправить в макете" disabled={!draft.trim()} onClick={()=>{setDraft("");setToast("Сообщение отправлено только внутри макета.")}}><ArrowRight size={19}/></button></div></div><footer><LockKeyhole size={10}/> Ваш диалог видит только наша команда</footer></section>}<button className="widget-launcher" aria-label={widgetOpen?"Закрыть чат":"Открыть чат"} onClick={()=>setWidgetOpen(value=>!value)}>{widgetOpen?<X/>:<MessageCircle/>}<span>Мы рядом</span></button></div></div>}
    </div><footer className="preview-footer"><span>01 / Тёплый, спокойный, рабочий</span><span>Вымышленные диалоги · действия остаются в макете</span><span>Windows · Android · сайт</span></footer>{toast&&<div className="preview-toast" role="status"><Check size={16}/>{toast}<button onClick={()=>setToast("")} aria-label="Закрыть подсказку"><X size={14}/></button></div>}
  </div>;
}
createRoot(document.getElementById("root")!).render(<Preview/>);
